AWSTemplateFormatVersion: '2010-09-09'
Description: ElasticsearchDomain resource

Parameters:
  DomainName:
    Description: User defined Elasticsearch Domain name
    Type: String
    Default: testelasticsearch
  ElasticsearchVersion:
    Description: User defined Elasticsearch Version
    Type: String
    Default: '7.8'
  InstanceType:
    Type: String
    Default: t3.small.elasticsearch
  Subnet:
    Type: AWS::EC2::Subnet::Id
  EsSgId:
    Type: AWS::EC2::SecurityGroup::Id

Resources:
  ElasticsearchDomain:
    Type: 'AWS::Elasticsearch::Domain'
    Properties:
      DomainName:
        Ref: DomainName
      DomainEndpointOptions:
        EnforceHTTPS: true
      ElasticsearchVersion:
        Ref: ElasticsearchVersion
      ElasticsearchClusterConfig:
        InstanceCount: '1'
        InstanceType:
          Ref: InstanceType
      EBSOptions:
        EBSEnabled: 'true'
        Iops: 0
        VolumeSize: 10
        VolumeType: gp2
      SnapshotOptions:
        AutomatedSnapshotStartHour: '0'
      AccessPolicies:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            AWS:
            - "*"
          Action:
          - es:*
          Resource: arn:aws:es:ap-south-1:552093781643:domain/testelasticsearch/*
      LogPublishingOptions:
        SEARCH_SLOW_LOGS:
          CloudWatchLogsLogGroupArn: >-
            arn:aws:logs:ap-south-1:552093781643:log-group:/aws/aes/domains/es-slow-logs
          Enabled: 'true'
        INDEX_SLOW_LOGS:
          CloudWatchLogsLogGroupArn: >-
            arn:aws:logs:ap-south-1:552093781643:log-group:/aws/aes/domains/es-index-slow-logs
          Enabled: 'true'
      AdvancedOptions:
        rest.action.multi.allow_explicit_index: 'true'
      VPCOptions:
        SubnetIds:
          - !Ref Subnet
        SecurityGroupIds:
          - Ref: EsSgId
      Tags:
        - Key: Name
          Value: TestEs
        - Key: Environment
          Value: Test

Outputs:
  DomainArn:
    Value:
      'Fn::GetAtt':
        - ElasticsearchDomain
        - DomainArn
  DomainEndpoint:
    Value:
      'Fn::GetAtt':
        - ElasticsearchDomain
        - DomainEndpoint
